### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ethan-Arrowood** [ginoskotheon/pythontuts#29]
- [ ] How to report a bug
- [ ] How to suggest a new feature/lesson
- [ ] How to set up your local development environment
- [ ] What you should be contributin
- [ ] . . .

**Comment by erictleung** [comment]
[Some ideas and other help](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines) on what to put into the `CONTRIBUTING.md` file.

**Comment by Ethan-Arrowood** [comment]
Added basic file. Could use some work 👍
