### ISSUE TITLE
Move to React App

### ISSUE THREAD

**Issue by Ethan-Arrowood** [ginoskotheon/pythontuts#30]
After a good deal of research and some extensive trial & error I couldn't figure out to efficiently build the routing and history functionality from scratch. SO I rebuilt the entire app using React and React Router 👍  Only took about a few hours to do, and I should be able to finish it this evening.

Heres my repo: https://github.com/Ethan-Arrowood/fcc-python-react-app

Heres the live (unfinished version): https://ethan-arrowood.github.io/fcc-python-react-app

This will be way easier to maintain and document as well.

**Comment by Ethan-Arrowood** [comment]
Y'all won't believe how many possibilities I just created by rewriting with React. Polishing off some tiny bugs and styling tomorrow then I'll push my code here.

**Comment by bgroveben** [comment]
Nice work @Ethan-Arrowood ! +1000 for rewriting the app in React/React Router.

**Comment by Ethan-Arrowood** [comment]
Its been done
